### ISSUE TITLE
FatesPFTIndexSwapper error

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#1134]
I just updated to cstm5.1.dev157 on Derecho.  When running FatesPFTIndexSwapper.py on the default parameter file provided with that tag, I get this error:

Creating Variable:  fates_alloc_organ_name
Traceback (most recent call last):
 File "FatesPFTIndexSwapper.py", line 274, in <module>
   main(sys.argv)
 File "FatesPFTIndexSwapper.py", line 196, in main
   out_var[:] = in_var[:]
 File "/python3.10/site-packages/scipy/io/_netcdf.py", line 1012, in __setitem__
   self.data[index] = data
ValueError: could not convert string to float: b'l'

I can run the script successfully on an older parameter file (5.1.dev.088). Has anyone else had this error?

**Comment by pollybuotte** [comment]
I found mt problem.  I am running locally and had not updated my version of the script.  It works as expected.  Sorry!
