### ISSUE TITLE
LAI sent to host has a forced minimum

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#261]
In EDCanopyStructureMod.F90:calc_areaindex()  we impose an artificial minimum on all area indices.  In other words, LAI/TAI/etc is not allowed to be lower than 0.1.

I think this is a pretty old artifact in the code, it has been left alone for this long just to retain B4B results in tests, but I think we really should remove this.

Its possible this was originally added to prevent a div0 somewhere, but we can find protections against this.

I could conceive that this minimum is generating some weird inconsistency that is affecting @jkshuman 's runs, but this is just a stab in the dark (might be worth testing its removal if no other ideas are generated).

**Comment by ckoven** [comment]
reopening this because of #739

**Comment by glemieux** [comment]
After checking to see if we could simply remove this again per the discussion https://github.com/NGEET/fates/discussions/1007#discussioncomment-5457762, testing shows that this is still and issue.  I'm seeing a floating point error for a threaded `aux_clm` test:

```
...
49699 102:MPT: #2  MPI_SGI_stacktraceback (
49700 102:MPT:     header=header@entry=0x7ffdc2c860d0 "MPT ERROR: Rank 102(g:102) received signal SIGFPE(8).\n\tProcess ID: 55323, Host: r13i3n34, Program: /glade/scratch/glemieux/ctsm-tests      /tests_ai-min-remove-aux-3/SMS_D_Lm6_P144x1.f45_f45_mg37.I2000Clm50"...) at sig.c:340
49701 102:MPT: #3  0x00002b2d04b8fe66 in first_arriver_handler (signo=signo@entry=8,
49702 102:MPT:     stack_trace_sem=stack_trace_sem@entry=0x2b2d14480080) at sig.c:489
49703 102:MPT: #4  0x00002b2d04b900f3 in slave_sig_handler (signo=8, siginfo=<optimized out>,
49704 102:MPT:     extra=<optimized out>) at sig.c:565
49705 102:MPT: #5  <signal handler called>
49706 102:MPT: #6  0x00000000018ed580 in edsurfaceradiationmod::ed_sunshadefracs (nsites=10,
49707 102:MPT:     sites=..., bc_in=..., bc_out=...)
49708 102:MPT:     at /glade/u/home/glemieux/ctsm/src/fates/biogeophys/EDSurfaceAlbedoMod.F90:1266
...
```
The `fates` suite test `ERS_Lm13.f10_f10_mg37.I2000Clm50Fates.cheyenne_gnu.clm-FatesCold` is failing somewhere during the `TotalBalanceCheck` call.

**Comment by rgknox** [comment]
@glemieux , for the SIGFPE(8) fail, can you confirm that line 1266 in the error matches this line from the recent tag:

https://github.com/NGEET/fates/blob/sci.1.65.3_api.25.4.0/biogeophys/EDSurfaceAlbedoMod.F90#L1266

**Comment by glemieux** [comment]
@rgknox confirmed :+1:
