### ISSUE TITLE
intersection of FATES and CLM5 variable soil depth

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#374]
I just got a weird crash, unrelated to the other various bugs we've been wrestling with (that conclusion based on the fact that it showed up both before and after those changes, and shows up in a different way from the ones we've been seeing lately).  Chatted with @rgknox about it, and we both believe it is from trying to run FATES with CLM5's variable soil depth.  The error showed up as seen below.  Probably we shouldn't be running FATES with the variable soil depth until this is sorted out, or at least be aware that this is a potential problem.

```
132: nstep         =       182398
132: errsol        =  -2.206668341386830E-007
30: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
30: nstep         =       182398
30: errsol        =  -1.642416691538529E-007
10: WARNING:  water balance error  nstep=       182398  local indexc=          104 
10:  errh2o=   1.026168128184096E-005
10: clm model is stopping - error is greater than 1e-5 (mm)
10: nstep                 =       182398
10: errh2o                =   1.026168128184096E-005
10: forc_rain             =   0.000000000000000E+000
10: forc_snow             =   0.000000000000000E+000
10: total_plant_stored_h2o_col =   0.000000000000000E+000
10: endwb                 =    1245.94856362796     
10: begwb                 =    1245.99963843958     
10: qflx_evap_tot         =   5.108507329977321E-002
10: qflx_irrig            =   0.000000000000000E+000
10: qflx_surf             =   0.000000000000000E+000
10: qflx_h2osfc_surf      =   0.000000000000000E+000
10: qflx_qrgwl            =   0.000000000000000E+000
10: qflx_drain            =   0.000000000000000E+000
10: qflx_drain_perched    =   0.000000000000000E+000
10: qflx_flood            =   0.000000000000000E+000
10: qflx_ice_runoff_snwcp =   0.000000000000000E+000
10: qflx_ice_runoff_xs    =   0.000000000000000E+000
10: qflx_glcice_dyn_water_flux =   0.000000000000000E+000
10: qflx_snwcp_discarded_ice =   0.000000000000000E+000
10: qflx_snwcp_discarded_liq =   0.000000000000000E+000
10: qflx_rootsoi_col(1:nlevsoil)  =   0.000000000000000E+000
10:  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
10:  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
10:  0.000000000000000E+000  4.049086548682799E-002  0.000000000000000E+000
10:  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
10:  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
10:  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
10:  0.000000000000000E+000
10: clm model is stopping
28: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
28: nstep         =       182398
28: errsol        =  -1.620585408090847E-007
143: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
143: nstep         =       182398
143: errsol        =  -2.666405407580896E-007
94: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
94: nstep         =       182398
94: errsol        =  -1.503968860561145E-007
10: calling getglobalwrite with decomp_index=          104  and clmlevel= column
10: local  column   index =          104
10: global column   index =           86
10: global landunit index =           26
10: global gridcell index =           11
10: gridcell longitude    =    239.750000000000     
10: gridcell latitude     =    35.2500000000000     
10: column   type         =            1
10: landunit type         =            1
10: ENDRUN:
10: ERROR in BalanceCheckMod.F90 at line 363                                       
10:                                                                                
10:                                                                                
10:                                                                                
10:                                                                                
10:                                                                                
10:                                       
10: ERROR: Unknown error submitted to shr_abort_abort.
11: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
11: nstep         =       182398
11: errsol        =  -1.225826053996570E-007
25: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
25: nstep         =       182398
25: errsol        =  -1.006897036859300E-007
73: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
73: nstep         =       182398
73: errsol        =  -1.200216956931399E-007
12: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
12: nstep         =       182398
12: errsol        =  -1.217612179971184E-007
119: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
119: nstep         =       182398
119: errsol        =  -1.020360969050671E-007
15: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
15: nstep         =       182398
15: errsol        =  -1.604901171958772E-007
23: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
23: nstep         =       182398
23: errsol        =  -1.218999159391387E-007
13: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
13: nstep         =       182398
13: errsol        =  -1.473987367717200E-007
9: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
9: nstep         =       182398
9: errsol        =  -1.198893642140320E-007
118: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
118: nstep         =       182398
118: errsol        =  -1.536847094030236E-007
1: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
1: nstep         =       182398
1: errsol        =  -1.472020585424616E-007
2: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
2: nstep         =       182398
2: errsol        =  -1.246141891897423E-007
22: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
22: nstep         =       182398
22: errsol        =  -1.450687250326155E-007
107: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
107: nstep         =       182398
107: errsol        =  -1.144171619671397E-007
134: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
134: nstep         =       182398
134: errsol        =  -1.108991227738443E-007
20: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
20: nstep         =       182398
20: errsol        =  -1.283870005863719E-007
24: WARNING:: BalanceCheck, solar radiation balance error (W/m2)
24: nstep         =       182398
24: errsol        =  -1.947835244209273E-007
10:Image              PC                Routine            Line        Source             
10:cesm.exe           00000000012655AD  Unknown               Unknown  Unknown
10:cesm.exe           0000000000D48C32  shr_abort_mod_mp_         114  shr_abort_mod.F90
10:cesm.exe           0000000000503CD5  abortutils_mp_end          77  abortutils.F90
10:cesm.exe           00000000006784DD  balancecheckmod_m         363  BalanceCheckMod.F90
10:cesm.exe           000000000050AF77  clm_driver_mp_clm         924  clm_driver.F90
10:cesm.exe           00000000004F9516  lnd_comp_mct_mp_l         451  lnd_comp_mct.F90
10:cesm.exe           0000000000430E14  component_mod_mp_         688  component_mod.F90
10:cesm.exe           0000000000417D59  cime_comp_mod_mp_        2652  cime_comp_mod.F90
10:cesm.exe           0000000000430B3D  MAIN__                     68  cime_driver.F90
10:cesm.exe           0000000000415C5E  Unknown               Unknown  Unknown
10:libc-2.19.so       00002AAAB190AB25  __libc_start_main     Unknown  Unknown
10:cesm.exe           0000000000415B69  Unknown               Unknown  Unknown
10:MPT ERROR: Rank 10(g:10) is aborting with error code 1001.
10:	Process ID: 6628, Host: r5i1n13, Program: /glade2/scratch2/charlie/fates_clm50_fullmodel_california_test2_3pfts_shrub2_nohydromort_respthrott_nospitfire_storage1pt8_3061dd9_8e96aef/bld/cesm.exe
10:	MPT Version: SGI MPT 2.15  12/18/16 02:58:06
10:
10:MPT: --------stack traceback-------
10:MPT: Attaching to program: /proc/6628/exe, process 6628
10:MPT: done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=3d290be00d48b823d3b71df2249e80d881bc473d"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=5409c48fdb15e90649c1407e444fbe31d6dc8ec1"
10:MPT: (no debugging symbols found)...done.
10:MPT: [Thread debugging using libthread_db enabled]
10:MPT: Using host libthread_db library "/glade/u/apps/ch/os/lib64/libthread_db.so.1".
10:MPT: Try: zypper install -C "debuginfo(build-id)=e97cfdb062d6f0c41073f2109a7605d0ae991c03"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=f43d7754940a14ffe3d9bd8fc9472ffbbfead544"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=0ea764119690f32c98faae9a63a73f35ed8b1099"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=15916519d9dbaea26ec88427460b4cedb9c0a6ab"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=79264652a62453da222372a430cd9351d4bbcbde"
10:MPT: (no debugging symbols found)...done.
10:MPT: Try: zypper install -C "debuginfo(build-id)=68682e9ac223d269cbecb94315fcec5e16b32bfb"
10:MPT: (no debugging symbols found)...done.
10:MPT: 0x00002aaaafac141c in waitpid () from /glade/u/apps/ch/os/lib64/libpthread.so.0
10:MPT: Missing separate debuginfos, use: zypper install glibc-debuginfo-2.19-35.1.x86_64
10:MPT: (gdb) #0  0x00002aaaafac141c in waitpid ()
10:MPT:    from /glade/u/apps/ch/os/lib64/libpthread.so.0
10:MPT: #1  0x00002aaab16215d6 in mpi_sgi_system (
10:MPT: #2  MPI_SGI_stacktraceback (
10:MPT:     header=header@entry=0x7ffffffee8f0 "MPT ERROR: Rank 10(g:10) is aborting with error code 1001.\n\tProcess ID: 6628, Host: r5i1n13, Program: /glade2/scratch2/charlie/fates_clm50_fullmodel_california_test2_3pfts_shrub2_nohydromort_respthrot"...) at sig.c:339
10:MPT: #3  0x00002aaab1574d6f in print_traceback (ecode=ecode@entry=1001)
10:MPT:     at abort.c:227
10:MPT: #4  0x00002aaab1574fda in PMPI_Abort (comm=<optimized out>, errorcode=1001)
10:MPT:     at abort.c:66
10:MPT: #5  0x00002aaab157528d in pmpi_abort__ ()
10:MPT:    from /opt/sgi/mpt/mpt-2.15/lib/libmpi.so
10:MPT: #6  0x0000000000e469a9 in shr_mpi_mod_mp_shr_mpi_abort_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/cime/src/share/util/shr_mpi_mod.F90:2132
10:MPT: #7  0x0000000000d48cd8 in shr_abort_mod_mp_shr_abort_abort_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/cime/src/share/util/shr_abort_mod.F90:69
10:MPT: #8  0x0000000000503cd5 in abortutils_mp_endrun_globalindex_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/src/main/abortutils.F90:77
10:MPT: #9  0x00000000006784dd in balancecheckmod_mp_balancecheck_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/src/biogeophys/BalanceCheckMod.F90:363
10:MPT: #10 0x000000000050af77 in clm_driver_mp_clm_drv_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/src/main/clm_driver.F90:924
10:MPT: #11 0x00000000004f9516 in lnd_comp_mct_mp_lnd_run_mct_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/src/cpl/lnd_comp_mct.F90:451
10:MPT: #12 0x0000000000430e14 in component_mod_mp_component_run_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/cime/src/drivers/mct/main/component_mod.F90:688
10:MPT: #13 0x0000000000417d59 in cime_comp_mod_mp_cime_run_ ()
10:MPT:     at /glade/u/home/charlie/ctsm/cime/src/drivers/mct/main/cime_comp_mod.F90:2652
10:MPT: #14 0x0000000000430b3d in MAIN__ ()
10:MPT:     at /glade/u/home/charlie/ctsm/cime/src/drivers/mct/main/cime_driver.F90:68
10:MPT: #15 0x0000000000415c5e in main ()
10:MPT: (gdb) A debugging session is active.
10:MPT: 
10:MPT: 	Inferior 1 [process 6628] will be detached.
10:MPT: 
10:MPT: Quit anyway? (y or n) [answered Y; input not from terminal]
10:MPT: Detaching from program: /proc/6628/exe, process 6628
10:
10:MPT: -----stack traceback ends-----
-1:MPT ERROR: MPI_COMM_WORLD rank 10 has terminated without calling MPI_Finalize()
-1:	aborting job
```

**Comment by ckoven** [comment]
this got fixed with #381
