### ISSUE TITLE
use_bedrock = .true. error

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#732]
I've found that when setting use_bedrock = .true. CLM-FATES fails when the surface data file has depth to bedrock set to 7 meters or less. CLM without FATES does not fail.  The first error in the traceback is:

144:MPT: #6  soilwaterplantsinkmod::compute_effecrootfrac_and_verttransink_default (
144:MPT:     bounds=..., num_filterc=22, filterc=..., soilstate_inst=...,
144:MPT:     waterfluxbulk_inst=...)
144:MPT:     at /glade/u/home/pbuotte/git/UI_fire/src/biogeophys/SoilWaterPlantSinkMod.F90:400
144:MPT: #7  0x00000000028ecebb in soilwaterplantsinkmod::compute_effecrootfrac_and_verttransink (bounds=..., num_hydrologyc=22, filter_hydrologyc=...,
144:MPT:     soilstate_inst=..., canopystate_inst=..., waterfluxbulk_inst=...,
144:MPT:     energyflux_inst=...)
144:MPT:     at /glade/u/home/pbuotte/git/UI_fire/src/biogeophys/SoilWaterPlantSinkMod.F90:129
144:MPT: #8  0x0000000001becd88 in hydrologynodrainagemod::hydrologynodrainage (
144:MPT:     bounds=..., num_nolakec=22, filter_nolakec=..., num_hydrologyc=22,
144:MPT:     filter_hydrologyc=..., num_urbanc=0, filter_urbanc=..., num_snowc=0,
144:MPT:     filter_snowc=..., num_nosnowc=22, filter_nosnowc=..., clm_fates=...,
144:MPT:     atm2lnd_inst=..., soilstate_inst=..., energyflux_inst=...,
144:MPT:     temperature_inst=..., water_inst=..., soilhydrology_inst=...,
144:MPT:     saturated_excess_runoff_inst=..., infiltration_excess_runoff_inst=...,
144:MPT:     aerosol_inst=..., canopystate_inst=..., scf_method=0x2b476f25c220,
144:MPT:     soil_water_retention_curve=0x2b476f71f620,
144:MPT:     topo_inst=0xac9e100 <clm_instmod_mp_topo_inst_>)

CLM branch = ctsm1.0.dev105_fates_api14.1.0.n01, commit aff0ff9f1a9767a9efba894410f96df5922b7f08
FATES branch = fire_seed_fixes, commit  c0f3957e58288d27500f7aff909873a1cae2b74d

**Comment by jkshuman** [comment]
@KatieMurenbeeld in your latest test of https://github.com/ESCOMP/CTSM/issues/1888 it seems that the modified bedrock is less than 7 meters. Can you confirm? 
I am wondering if this old FATES issue is still a problem.

**Comment by KatieMurenbeeld** [comment]
Yes, in those runs for https://github.com/ESCOMP/CTSM/issues/1888 zbedrock was set to 4.9m (orig) and 1m (mod).  However, I only ran these as a test/teaching tool for 10 years. 

I will reply to this comment with the CLM and FATES branches.
